version: '3.8'
services:
  chrysedgeportal:
    image: chryscloud/chrysedgeportal:0.0.7
    build: web/
    depends_on:
      - chrysedgeserver
      - redis
    ports:
      - "8905:8905"
    networks:
      - chrysnet
  chrysedgeserver:
    image: chryscloud/chrysedgeserver:0.0.7
    build: server/
    restart: always
    depends_on:
      - redis
    entrypoint: /app/main
    ports:
      - "8909:8909"
      - "50005:50005"
    volumes:
      - /data/chrysalis:/data/chrysalis
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - chrysnet
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks: 
      - chrysnet

networks:
  chrysnet:
    name: chrysnet
